echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "I m learning branching in git"
echo " I am learning Devops and I am from Batch 30 "
echo "I am from Devops and cloud team"
echo "I am DevOps-2"
echo " I am just switch in my INC212002 branch"
echo " I am adding new Line "
echo " Iam demonstrating git pull vs got fetch "